### ISSUE TITLE
Move tree-sitter logic to language-service

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/language-server#28]
The [@cucumber/monaco](https://github.com/cucumber/monaco) module needs the tree-sitter functionality, but not the [@cucumber/language-server](https://github.com/cucumber/language-server) functionality. Since `@cucumber/monaco` depends on [@cucumber/language-service](https://github.com/cucumber/language-service), we should move the tree-sitter functionality there.

It used to be in [@cucumber/language-service](https://github.com/cucumber/language-service), but it was removed in [0.10.0](https://github.com/cucumber/language-service/blob/main/CHANGELOG.md#0100---2021-11-08). Let's undo that.

**Comment by olleolleolle** [comment]
Thanks for the analysis on these issues, it shakes loose a few things! Context matters.
