### ISSUE TITLE
Add to https://langserver.org/

### ISSUE THREAD

**Issue by mattwynne** [cucumber/language-server#31]
There's a list here of different language servers, it would be nice to be visible in that list once we're ready.

You can ask to be added by submitting a PR/issue to https://github.com/langserver/langserver.github.io

**Comment by aslakhellesoy** [comment]
Sumbitted:

* https://github.com/langserver/langserver.github.io/pull/279
* https://github.com/microsoft/language-server-protocol/pull/1451

**Comment by aslakhellesoy** [comment]
Both are merged now, so closing this.
