### ISSUE TITLE
Windows test fails on ENAMETOOLONG

### ISSUE THREAD

**Issue by olleolleolle** [cucumber/language-server#6]
**Describe the bug**

There is 1 failing test which can not run on Windows, and it fails with an ENAMETOOLONG error.

Should that test be skipped, or amended, for that platform?

**To Reproduce**
1. Go to any CI test output for the windows target
2. Click on the `install-test` step
3. See error

**Expected behavior**

✅ green tests.

**CI:**
 - OS: windows-latest
 - Browser n/a
 - Version: Node 16.x

**Comment by aslakhellesoy** [comment]
This is fixed on `main`
