### ISSUE TITLE
Pretty-Quick conflict with Prettier v3 causing pre-commit hook to fail

### ISSUE THREAD

**Issue by binhtran432k** [cucumber/language-server#92]
### 🤔 What's the problem you've observed?

I'm encountering an issue where the pre-commit hook using `pretty-quick` is failing, preventing me from creating new commits. The issue seems to stem from a conflict with Prettier v3.

### ✨ Do you have a proposal for making it better?

I think `pretty-quick` is outdated, it hasn't been updated for 2 years. We should temporarily disable the pre-commit hook now.

### 📚 Any additional context?

See https://github.com/azz/pretty-quick/issues/168

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/developer_experience.md)*

**Comment by kieran-ryan** [comment]
Cheers @binhtran432k - have observed the same. I'll take a look when I can for a suitable alternative to this package. Thanks!
